<?php

/***************************************************************
 * Extension Manager/Repository config file for ext "lp_iframe".
 *
 * Generated by ext 07-03-2016 20:35 UTC
 *
 * https://github.com/t3elmar/Ext
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array (
	'title' => 'iFrame for HTML5 Websites',
	'description' => 'Yet another iFrame extension with HTML5 support. Rendered with TypoScript. Doc: http://docs.typo3.org/typo3cms/extensions/lp_iframe/ and Git: https://github.com/lars85/TYPO3-Extensions-lp_iframe/',
	'category' => 'plugin',
	'version' => '1.2.7',
	'state' => 'stable',
	'uploadfolder' => 0,
	'createDirs' => '',
	'clearcacheonload' => 0,
	'author' => 'Lars Peipmann',
	'author_email' => 'Lars@Peipmann.de',
	'author_company' => '',
	'constraints' => 
	array (
		'depends' => 
		array (
			'typo3' => '6.0.0-7.6.99',
		),
		'conflicts' => 
		array (
		),
		'suggests' => 
		array (
		),
	),
    'comment' => 'Updates for TYPO3 Version 7.6.x',
);

