<?php

/*********************************************************************
* Extension configuration file for ext "lp_iframe".
*
* Generated by ext 15-06-2014 16:35 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'iFrame for HTML5 Websites',
  'description' => 'Yet another iFrame extension with HTML5 support. Rendered with TypoScript. Doc: http://docs.typo3.org/typo3cms/extensions/lp_iframe/ and Git: https://github.com/lars85/TYPO3-Extensions-lp_iframe/',
  'category' => 'plugin',
  'author' => 'Lars Peipmann',
  'author_email' => 'Lars@Peipmann.de',
  'author_company' => '',
  'shy' => '',
  'priority' => '',
  'module' => '',
  'state' => 'stable',
  'internal' => '',
  'uploadfolder' => '0',
  'createDirs' => '',
  'modify_tables' => '',
  'clearCacheOnLoad' => 0,
  'lockType' => '',
  'version' => '1.2.7',
  'constraints' => 
  array (
    'depends' => 
    array (
      'typo3' => '6.0.0-6.2.99',
    ),
    'conflicts' => 
    array (
    ),
    'suggests' => 
    array (
    ),
  ),
  'comment' => 'Updates for TYPO3 Version 6.2',
  'user' => 'lars85',
);

?>