<?php

/*********************************************************************
* Extension configuration file for ext "lp_iframe_f4x".
*
* Generated by ext 30-08-2013 13:09 UTC
*
* https://github.com/t3elmar/Ext
*********************************************************************/

$EM_CONF[$_EXTKEY] = array (
  'title' => 'iFrame for HTML5 Websites (for TYPO3 Version 4.x)',
  'description' => 'Yet another iFrame extension with HTML5 support for TYPO3 Version 4.x. Rendered with TypoScript. Doc: http://docs.typo3.org/typo3cms/extensions/lp_iframe_f4x/ and Git: https://github.com/lars85/TYPO3-Extensions-lp_iframe/',
  'category' => 'plugin',
  'author' => 'Lars Peipmann',
  'author_email' => 'Lars@Peipmann.de',
  'dependencies' => 'extbase',
  'author_company' => '',
  'shy' => '',
  'priority' => '',
  'module' => '',
  'state' => 'stable',
  'internal' => '',
  'uploadfolder' => '0',
  'createDirs' => '',
  'modify_tables' => '',
  'clearCacheOnLoad' => 0,
  'lockType' => '',
  'version' => '1.2.6',
  'constraints' => 
  array (
    'depends' => 
    array (
      'typo3' => '4.5.0-4.7.99',
      'extbase' => '',
    ),
    'conflicts' => 
    array (
    ),
    'suggests' => 
    array (
    ),
  ),
  'comment' => 'Solved problem with PHP version 5.3',
  'user' => 'lars85',
);

?>